// Copyright 2019-2022 Tauri Programme within The Commons Conservancy
// SPDX-License-Identifier: Apache-2.0
// SPDX-License-Identifier: MIT

/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function run(args: Array<string>, binName?: string | undefined | null, pkgManager?: string | undefined | null): void
