# Copyright 2019-2022 Tauri Programme within The Commons Conservancy
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

name = "create-tauri-app"
main = "index.js"
compatibility_date = "2022-08-04"

[[rules]]
type = "Text"
globs = ["**/*.sh", "**/*.ps1", "index.html"]
fallthrough = true
