# Copyright 2019-2022 Tauri Programme within The Commons Conservancy
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

name: deploy .{sh,ps1} scripts worker

on:
  push:
    branches:
      - dev
    paths:
      - '.github/workflows/deploy-scripts-worker.yml'
      - 'worker/**'

jobs:
  deploy:
    # prevents this action from running on forks
    if: github.repository_owner == 'tauri-apps'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Install pnpm
        uses: pnpm/action-setup@v6

      - name: Install Node.js
        uses: actions/setup-node@v7
        with:
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - uses: cloudflare/wrangler-action@v4
        with:
          command: deploy
          workingDirectory: 'worker'
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
