# Copyright 2019-2022 Tauri Programme within The Commons Conservancy
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

name: deploy .{sh,ps1} scripts worker

on:
  push:
    branches:
      - dev
    paths:
      - '.github/workflows/deploy-scripts.yml'
      - 'packages/worker/**'

jobs:
  deploy:
    # prevents this action from running on forks
    if: github.repository_owner == 'tauri-apps'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cloudflare/wrangler-action@2.0.0
        with:
          command: publish
          workingDirectory: 'packages/worker'
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
